baseURL = "https://blog.kis9a.com/"
title = "kis9a - blog"

[params]
thumbnail = "kis9a.jpg"
favicon = "favicon.ico"
headertitle = "KIS9A"
description = "kis9a blog site | blog.kis9a.com"
author = "kis9a"
avatar = "https://avatars2.githubusercontent.com/u/65019715?s=400&u=731fbe172c33e4511a105e3cc5e697c9e3c87fd3&v=4"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
pre = "<i class='fas fa-search'></i>"
weight = 2
identifier = "search"
title = "Search"
url = "/search"
