baseURL: "https://blog.kis9a.com"
title: kis9a - blog
paginate: 6
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: kis9a - blog
    description: "kis9a blog site for output articles contents | blog.kis9a.com | github.com"
    # author: kis9a

    images: "<link or path of image for opengraph, twitter-cards>"
    draft: false
    ShowToc: false
    TocOpen: false
    hidemeta: false
    disableShare: true
    ShowReadingTime: false
    ShowShareButtons: false
    ShowCopyright: false;
    comments: false
    defaultTheme: light
    homeInfoParams: false
    hideSummary: true
    disableThemeToggle: true
    disableSpecial1stPost: true
    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "kis9a"
        icon: false

    profileMode:
        enabled: false # needs to be explicitly set
