baseURL = "https://blog.kis9a.com/"
title = "kis9a"
description = "kis9a blog site | blog.kis9a.com"
theme = "kiss"
languageCode = "en"
copyright = "&copy; <a href=\"http://github.com/kis9a\">kis9a</a> 2021"
disqusShortname = "kis9a"
googleAnalytics = ""
Paginate = 8
enableRobotsTXT = true

[params]
thumbnail = "kis9a.jpg"
favicon = "favicon.ico"
headertitle = "KIS9A"
description = "kis9a blog site | blog.kis9a.com"
author = "kis9a"
avatar = "https://avatars2.githubusercontent.com/u/65019715?s=400&u=731fbe172c33e4511a105e3cc5e697c9e3c87fd3&v=4"

[[params.nav]]
url = "/search"
fa_icon = "fa-search"

[[params.nav]]
url = "/tags"
fa_icon = "fa-hashtag"

[[params.link]]
url = "https://nav.kis9a.com"
fa_icon = "fa-link"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "search"
pre = "<i class='fas fa-info'></i>"
title = "Search"
url = "/search"
weight = 4

[params.rss]
includeContent = true
authorName = "kis9a"
authorEmail = "kis9ax@gmail.com"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = ""
enableSocial = true
homeTitle = ""
related = true
codeCopy = true
taxonomiesCount = true

[params.social]
twitter = "kis9a"
github = "kis9a"
email = ""
linkedin = ""
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml"

[params.social.config]
platforms = ["github","twitter"]
